### ISSUE TITLE
C4 Not Glowing

### ISSUE THREAD

**Issue by gazababon123** [iseekwonderful/csgoGlow#113]
Terrorist have been smoking c4, is there a way i can make it glow?

**Comment by DooubleO** [comment]
https://www.youtube.com/watch?v=fCyDacGXgtI

**Comment by aKalisch** [comment]
For C4 glow you need to get the Entity and enable Glow for it.

Maybe I'll check that later.

**Comment by gazababon123** [comment]
@DooubleO no, but that is only for when the c4 is planted, i want to know if it was just dropped, so it will be an advantage for me when i am in counter-terrorist.

**Comment by iseekwonderful** [comment]
@gazababon123 It seems that due to the PVS (Potentially Visible Set) system of csgo, if the carrier of C4 or the drop position of the C4 isn't 'visible' to you, server won't send the information of C4 to you, than you can't glow the C4.
Now assume that server's PVS system think you can 'see' the C4, you can do this:
loop entities list -> get the classID of entity -> get the C4 -> glow it

**Comment by DooubleO** [comment]
All i'm saying is if you need to depend on this hack to play the game, then you are down right terrible. Use the hack as a guide every now and then, otherwise you never get better.

**Comment by gazababon123** [comment]
@iseekwonderful yay thx :D i did it, thankyou so much :D

**Comment by Fury2211** [comment]
Hello, how I can change skins? OR knife ? Maybe some code or program like Skin Changer?
