### ISSUE TITLE
Enhancement for Walls

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#129]
how can i change the colour depending on visibility of the player?

**Comment by aKalisch** [comment]
Still a simple answer: You can't as long you don't implement Visibility checks into the hack.

To add visibility checks you need to implement a BSP parser.

**Comment by iseekwonderful** [comment]
BSP parser is not enough, a additional Entity Parser and external visiable ray trace is needed

**Comment by aKalisch** [comment]
@iseekwonderful yes i know. But a BSP parser is the first step when you are external.
You could also work with m_bSpotted and m_bSpottedByMask (but it's slow)

**Comment by gabsens** [comment]
@aKalisch BSP parsing won't lead you anywhere near a usable aimbot

**Comment by aKalisch** [comment]
@gabsens I've already implemented bsp parsing + TraceRay Checks into my Hack. Working like a charm.

**Comment by aKalisch** [comment]
Using it for Glow Visibility and Aimbot. I think my Aimbot looks very legit as it works with closest bone to crosshair and some other checks. It picks the closest HITBOX and aims smooth (bezir curves) to it. After a period of ticks it locks off and gets the next best bone. With some good crosshairplacement it's almost headshot without looking obvious. But I will not release this because there are so much noob kids,  that will release some P2C out of it.

**Comment by gabsens** [comment]
@aKalisch you did achieve calls to the in-game TraceRay function ?
