### ISSUE TITLE
Multihack

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#151]
Did you guys make this and these guys are selling it? Or are they legit?
http://csgo.cheatsformacs.com

**Comment by Noriaela** [comment]
I'll test it out for you mate :D

**Comment by Noriaela** [comment]
I'm messing with it atm and it seems like it has a trial type thing were you can only use/open it twice and then after you need to pay or put a seriel key in 
Update: Well I cant tell you if it works because the idiots that made it like I said give you 2 chances to use it. If you wanna buy it go for it but be warned they may scam you.
Btw I never got and virus alert

**Comment by iPredictable** [comment]
@sonicrules11 Update, I bought it and its legit. but its very rage hacky. and it already got 2 of my account untrusted banned.

**Comment by stepucracr** [comment]
@PredictEr "but its very rage hacky" what do you mean with rage hacky? does it work? dont wanna keep fighting this code every time it breaks

**Comment by bertrand2012** [comment]
@PredictEr Have you already got a VAC?!

**Comment by iPredictable** [comment]
@acer2245 Not VAC, untrusted. If you rage hack you get untrusted ban

**Comment by stepucracr** [comment]
@PredictEr you mean play aggressively obvious? like killing everyone constantly with the aimbot? :P

**Comment by iPredictable** [comment]
@stepucracr It works fine. The aimbot just locks on really hard. The wallhack is copied from this hack. It's really good. but the aimbot is really trippy, just locks on people across the map constantly

**Comment by iPredictable** [comment]
@stepucracr yeah if you ragehack with any hack you get an untrusted ban. Its not from VAC or overwatch. even if ur in casual

**Comment by PredictEr** [comment]
@stepucracr @acer2245 Its just that this multihack has such a simple aimbot, wh

**Comment by iPredictable** [comment]
@stepucracr @acer2245 Its just that this multihack has such a simple aimbot, which isn't designed for legit play at all.

**Comment by stepucracr** [comment]
@PredictEr ha I guess thats normal for most aimbots...

**Comment by stepucracr** [comment]
@PredictEr does the bhop work well? I saw they have triggerbot too, have you tried it? Seems better for playing legit

**Comment by bertrand2012** [comment]
@PredictEr What happens on a untrusted ban? Like can you still play? What will be different?

**Comment by Noriaela** [comment]
Ok I dont like buying hacks myself unless I know they are trusted thank you for telling me @PredictEr

**Comment by stepucracr** [comment]
@sonicrules11 from what I understand, it's not the hack that's untrusted, it's the way that you use the hack. If you're going around zapping head to head in an instant, because you're aimbotting like cray, the game's going to pick up on it and will decide not to trust you. Im curious how the triggerbot works

**Comment by Mike2445** [comment]
Their hack is awesome. But  guys, rlly? don't use aimbot anywhere. it's easily noticeable, and it's super easy to get over-watched, if you want just have fun with aimbot, go play with bots on your local server, on where you can't get over-watched, i guess non-vac servers are not being over-watched. 
Im playing around week on this, playing just a little and sometimes obviously, with options like: wallhack, trigger bot, auto bhop and i did not get banned.

@PredictEr I have been playing around a little bit with aimbot locally, just set activation like 200-600. works better

**Comment by stepucracr** [comment]
@Mike2445 you got it too? hows the triggerbot? does it work well, like with snipers?

**Comment by Mike2445** [comment]
works incredibly well. But you must be playing fullscreen to make it work properly.

**Comment by aKalisch** [comment]
PLease guys. If you don't know how anti-cheats work, don't talk about it.

As I noticed you get untrusted. As I further noticed their aimbot locks on without FOV and stuff like that.
So the untrusted might come that the aimbot sets view angles that don't exists (x angle > 89 || x angle < -89 || y angle > 180 || y angle < -180) ... that's one of the things that can get untrusted. Use the Aimbot play a bit on local server against bots and then watch into ur console. If there are Errors like Bad SetAng or something like that you are banned most likely because of this.

on www.unknowncheats.me are so many threads about anti-cheat and overwatch. So before asnwering questions in a stupid way without any knowledge about the system first get the right informations.

**Comment by aKalisch** [comment]
@Mike2445 I bet I was overwatched so many times on my way from MG1 to DMG but never get a Ban. Playing with Aimbot (yeah on Mac). Also I play prime matchmaking without any problems.

A good and legit aimbot will not be noticed by overwatch, too... Remember Overwatch uses Tick 32 Demos. If your Aimbot is almost legit the rest will do Tick32 ;-)

One more Hint: Playing against Bots will not prevent you from VAC!!! You need to start CS:GO with the -insecure flag!

**Comment by Mike2445** [comment]
@aKalisch  Actually i have been playing with aimbot on local server with bots, without insecure flag. Everything was on as well achievements and i did dont get banned while aimbot did pretty crazy things.

**Comment by Acornay** [comment]
If anyone wants a discount if they're buying the hack, go ahead and ask me.

**Comment by iPredictable** [comment]
@aKalisch u ever gonna release that smooth aimbot of urs?

**Comment by aKalisch** [comment]
1 simple word: NO!
When I'll release something aimbot like i'll just release a source. You need to implement it urself.

BUT! This "issue" is closed. So stop discussing!
