### ISSUE TITLE
Can you get VAC banned for using terminal?

### ISSUE THREAD

**Issue by bromi5** [iseekwonderful/csgoGlow#172]
I was just wondering if you could get VAC banned for using terminal because doesn't VAC run a scan through your computer or something to check if your running something suspicious?
thank you,
bromi5

**Comment by ghost** [comment]
No,

It is near impossible to get VAC banned on the Mac OS X operating system, because Valve has not developed a proper VAC system for Macs yet. The only ban you could possibly get resulting from using this hack would be from the Overwatch system, because when too many people report you in a competitive match a demo will be automatically sent to people who have earned Overwatch. (Depending on your rank, say for example if you are around the Gold Nova level the demo will be sent to Gold Nova Overwatchers).

**Comment by bromi5** [comment]
ok thanks

**Comment by aKalisch** [comment]
@somerandomdud Don't tell false informations to other people.
VAC is still active at macOS ... But it's useless through security of macOS ... Hacks using memory reading -> macOS disallow this on Ring3 ... So hacks must run through root ... VAC still runs at Ring3 ... So VAC doesn't recognize any hacks running as root.
But it's active.

Overwatch Bans and untrusted Bans are still active on macOS as they are depending on other mechanism than signature scans of running processes.
