### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by njmii** [iseekwonderful/csgoGlow#191]
i dont know why, but it crashes alot. i need to restart my pc and run it . after the update there is no pattern, after one game (deathmatch) it crashes. i cant study why and how. i tried restart, paste the wall exe many times, exit all apps .

**Comment by Noriaela** [comment]
You wanna speak english first?

**Comment by njmii** [comment]
Im sorry for not "speaking" in english @sonicrules11 , it is not my first language however, i will invest some time to construct  a proper sentence after this. 

So as we all know, we ate require to have csgo and terminal to run this program. In my 2 weeks of experience, i need to restart my mac whenever i want to run csgoglow or my csgo will crash. 

During this two weeks of constant crashing, i gather statistics and data to study why this such event occur. I have a new macbook pro i do not
Think hardware is the culprit behind this crash activity. 

So here is the details how it crash.
The glow running smoothly for exactly ONE round (deathmatch) and when i wanted to go to the next map (SECOND round) it loaded but as soon as i walk, csgo crashed. The crash pattern is the same in matchmaking, where every round the game crash (if i use csgoglow)

I ran root mode using sudo -s and exited all the apps besides csgo and terminal.

Again, i am sorry for my lack use of english language and i have zero knowledge in using terminal. It would
Be appreciated if the dev and the community could help me resolve my issue.

Thankyou
Njmii

**Comment by Kazzaowo** [comment]
i dont understand why all of you who seem to know your stuff have to be such assholes. Honestly some of us want to fucking put time into this shit but you guys act like you deserve your dicks sucked 24/7 we all started somewhere. Being a cunt is an option. Stop picking it and try and help.

**Comment by Noriaela** [comment]
@njmii thank you its just hard to understand what you were saying. Yeah the glow has crash problems I don't entirely know whats causing it atm tho I'm using a different wall hack https://github.com/vikingmicrowave/Microwave-Open-Source its really good since its an internal hack I haven't had any issues with the hack.
@KazzaKING I wasn't trying to be an asshole it was just hard to understand what he was saying no need for you to point out I'm being a dick if you don't like mean people you may wanna leave the internet :) have a good day

**Comment by njmii** [comment]
update: i run mat_queue_ 2 , it doesnt crash at all but fps dropped to 18

**Comment by njmii** [comment]
update: mat_queue_mode 2 solve the crash issue, but mat_queue_mode 1 help my fps stable.

whenever im about to finish rounds i run mat_queue_mode 2 and when im actually playing i ran mat_queue_mode 1.

**Comment by brendon11** [comment]
i like how @sonicrules11 tries to act like hes familiar with all this shit, but then I see him begging people on unknowncheats for help, lmao

**Comment by MyNameIsLebronJames** [comment]
LOL

**Comment by Noriaela** [comment]
@brendon11 I like how acting like an asshole solved something :) btw i've asked for help on unkowncheats around once or twice

**Comment by Noriaela** [comment]
@brendon11 If you'd like to link the times i've asked for help that be greatly appreciated because I can link al the times i've asked. I didnt know it was wrong to ask for help

Edit: 
![Tell me what that says](https://cloud.githubusercontent.com/assets/22671423/23684565/c65915f0-035c-11e7-85bf-449d166583d6.png)

**Comment by njmii** [comment]
Closing this thread because none of the "answer" that i received help me solving this issue using this hacks.

to those who have same issue as mine , here what you can do : 

1. when u enter the game , type in mat_queue_mode 2 it will drop ur FPS drasticaly
2. 6 second after u run the game type in mat_queue_mode 1 so that ur FPS will go back up
3. repeat step 1 and 2 EVERYTIME u load a new map 

reason.

1. mat_queue_mode 2 = somehow it stop the game from crashing but drop ur FPS that is why this is essential

2. mat_queue_mode 1 = use this to make ur game PLAYABLE
