### ISSUE TITLE
I need help on actually installing

### ISSUE THREAD

**Issue by gayslut1234** [iseekwonderful/csgoGlow#234]
Im confused on what to do after it says run with **ROOT** like do i go in terminal and do sudo -s (and drag what file in?) im confused pls help thanks

- gayslut1234

**Comment by drauf** [comment]
Yes, you are correct.
Although, the cheat is outdated. It requires some basic knowledge to fix it but judging by your question, you might be better off using a public cheat for MacOS. You can find one by googling `gosx` (currently it's definitely the best cheat for Macs, but I believe there is no longer a free version available).
There are also at least two other cheats available - xOracle and vlone. I've used the free version of xOracle for a couple minutes a few months ago and it worked fine, although it was a lot worse than gosx. I'd recommend staying away from vlone, because they included (still include?) a trojan in their cheat.
