### ISSUE TITLE
Doesn't Work in latest version of csgo?

### ISSUE THREAD

**Issue by Loltestaccountplz** [iseekwonderful/csgoGlow#59]
I ran the file and the walls isn't working? I ran it with root while the game was running got into a offline game with bots, the normal glow esp wasn't showing. I'm assuming its because of the newest update to csgo?

**Comment by ggothreau** [comment]
@Loltestaccountplz:
Please check previous issues for more information on this. Other users have made tutorials and tools to find offsets after each update.

Previous issues here:
https://github.com/iseekwonderful/csgoGlow/issues/33
https://github.com/iseekwonderful/csgoGlow/issues/43

Just to reiterate, after each update to CSGO the locations in memory change. Because csgoGlow references specific areas in memory those references stop working after each update. You need to find the new memory address offsets (either doing it yourself or finding the new values here), placing them in the code, and recompiling the tool.

That said, I am including the new offsets here, but I highly recommend you teach yourself how to do this. At the very least it's an educational experience in memory manipulation.

uint64_t glowInfoOffset = 0x5955F00;
uint64_t LocalPlayerBase = 0x5146638;
uint64_t playerBase = 0x50C3248;

**Comment by Loltestaccountplz** [comment]
@ggothreau thanks sorry I'm kind of new to this stuff lol

**Comment by ggothreau** [comment]
@Loltestaccountplz no worries, my dude. We all started off being new to this stuff. But if you learn it then you don't have to come and check the issues page every time there is an update.
