### ISSUE TITLE
Trouble on OS X Yosemite

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#62]
how do i activate it can u add me on steam and tell me my name ins JaLonG im VERY confused

**Comment by tr1kyyy** [comment]
@extrenebiibues Bro...directions are in the description.

**Comment by ghost** [comment]
@extrenebiibues Download the zip, run the project in xcode with root permission.

**Comment by ggothreau** [comment]
The whole point of this project is to be educational. If you're not comfortable with C/C++, memory hacking or basic command line usage (or not willing to take the time to learn) then you're going to have a bad time.

You need xcode from the App Store. Then you need to update the offsets to the most recent published values (since they change between every update to CSGO). You then need to compile/build the project, and then run the resulting application / product under root.

**Comment by joejoepojoe** [comment]
I built the executable using Xcode, and then used bash to run the executable, and when i run it, i simply get the message "Access denied", I have root enabled on my mac and am not sure what is causing this? Any clues as to what I am doing wrong. I tried running a different executable and it worked just fine, unless i built it wrong.
Last login: Sat Aug  6 22:40:24 on ttys000

uss-iMac:~ us$ dsenableroot
username = us
user password:
root password:
verify root password:

dsenableroot:: ***Successfully enabled root user.
uss-iMac:~ us$ sudo -s
bash-3.2# cd Desktop
bash-3.2# ./Wall
bash: ./Wall: Permission denied

**Comment by gabsens** [comment]
@joejoepojoe are you running el capitan?

**Comment by markietard** [comment]
@gabsens is there any more detail tutorial about this? Because I'm new to the coding community and I don't quite understand how it works. I need some help please

**Comment by ggothreau** [comment]
Just use the `sudo` command. 
- Open a new Terminal.app window.
- Type `sudo` (put a space after sudo).
- Drag the compiled `Wall` product from xcode to the terminal window. (it should show the full path to your Wall executable).
- Hit enter and enter your password.

You need csgo running already before you do this, of course.

**Comment by joejoepojoe** [comment]
I sorted it :) And yes, El Capitan
