### ISSUE TITLE
Stupid question.

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#90]
When spectating u can see players everywhere with the glow but using the same type of glow how come we cant achieve that?

**Comment by extrenebiibues** [comment]
im not asking for u to do it im asking why it isnt possible btw

**Comment by aKalisch** [comment]
Can you explain what you mean?

**Comment by extrenebiibues** [comment]
@aKalisch u cant see say the enemy team in their spawn through a ton of walls, how come?

**Comment by sacredgeo** [comment]
I like that you can't see the entire enemy team if they are far away. It would be overwhelming to see every player. This hack shows you players that are nearby.

**Comment by extrenebiibues** [comment]
@sacredgeo but i would rather know what site the enemy is going to, stack it and then toggle off

**Comment by aKalisch** [comment]
As specator there is not that much performance needed. So the engine can show Enemies on the complete map. Due to performance the engine hides your enemies as long the engine don't need to render them.

In Source SDK this is called area portals.
It hides everything that doesn't need to be rendered as you can't see it.

So there is no way to fix this. This is map dependend.
